# Netlify configuration for Mahaveer Bhavan Web Admin

[build]
  # Directory with package.json
  base = "web/admin"

  # Build command
  command = "npm run build"

  # Output directory (relative to base)
  publish = "dist"

# Environment variables (configure these in Netlify dashboard)
# VITE_SUPABASE_URL = "your_supabase_project_url"
# VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key"

# Redirect rules for client-side routing (SPA)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Production environment settings
[context.production]
  command = "npm run build"

[context.production.environment]
  NODE_VERSION = "18"

# Deploy preview settings
[context.deploy-preview]
  command = "npm run build"

# Branch deploy settings
[context.branch-deploy]
  command = "npm run build"
